/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bean.cad_cli_bean;
import conexao.ConnectionConexao;
import dao.cad_cli_dao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16127512021.2
 */
public class tela_cadastro_client extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastro_client
     */
    public tela_cadastro_client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        lblMensagem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("Id:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, 30, 30));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, -1, 30));

        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Cpf", "Endereço", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblclientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 610, 110));
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 300, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 44, 60, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, 50, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 100, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Telefone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 134, 90, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("E-mail:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 164, 70, 30));
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 190, -1));
        getContentPane().add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 210, -1));
        getContentPane().add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, -1));
        getContentPane().add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 230, -1));

        jButton7.setText("Alterar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 203, -1, 30));

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 0));
        jButton1.setText("Cadastrar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 230, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = ConnectionConexao.abrirConexao();
        cad_cli_bean cb = new cad_cli_bean();
        cad_cli_dao cd = new cad_cli_dao(con);

        cb.setNome_cli(txtnome.getText());
        cb.setCpf_cli(txtcpf.getText());
        cb.setEndereco_cli(txtendereco.getText());
        cb.setTelefone_cli(txttelefone.getText());
        cb.setEmail_cli(txtemail.getText());

        lblMensagem.setText(cd.inserir(cb));
        ConnectionConexao.fecharConexao(con);

        txtnome.setText("");
        txtcpf.setText("");
        txtendereco.setText("");
        txttelefone.setText("");
        txtemail.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection con = ConnectionConexao.abrirConexao();
        cad_cli_dao cd = new cad_cli_dao(con);
        List<cad_cli_bean> listaclientes = new ArrayList<cad_cli_bean>();
        listaclientes = cd.listarTodos();
        DefaultTableModel tbm = (DefaultTableModel) tblclientes.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (cad_cli_bean cb : listaclientes) {
            tbm.addRow(new String[1]);
            tblclientes.setValueAt(cb.getId_cli(), i, 0);
            tblclientes.setValueAt(cb.getNome_cli(), i, 1);
            tblclientes.setValueAt(cb.getCpf_cli(), i, 2);
            tblclientes.setValueAt(cb.getEndereco_cli(), i, 3);
            tblclientes.setValueAt(cb.getTelefone_cli(), i, 4);
            tblclientes.setValueAt(cb.getEmail_cli(), i, 5);

            i++;
        }
        ConnectionConexao.fecharConexao(con);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclientesMouseClicked
        int linha_selecionada = tblclientes.getSelectedRow();

        txtid.setText(tblclientes.getValueAt(linha_selecionada, 0).toString());
        txtnome.setText(tblclientes.getValueAt(linha_selecionada, 1).toString());
        txtcpf.setText(tblclientes.getValueAt(linha_selecionada, 2).toString());
        txtendereco.setText(tblclientes.getValueAt(linha_selecionada, 3).toString());
        txttelefone.setText(tblclientes.getValueAt(linha_selecionada, 4).toString());
        txtemail.setText(tblclientes.getValueAt(linha_selecionada, 5).toString());
    }//GEN-LAST:event_tblclientesMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtid.setText("");
        txtnome.setText("");
        txtcpf.setText("");
        txtendereco.setText("");
        txttelefone.setText("");
        txtemail.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int cont = 0;
        int indice = tblclientes.getSelectedRow(); // mostra o valor da linha selecionada
        // conta quantas pessoas estão selecionadas na tabela obs: i = linha e 0 = coluna. obs: matriz
        for (int i = 0; i < tblclientes.getRowCount(); i++) { // percorre todas as linhas da tabela para verificar a existência de itens
            if (tblclientes.getValueAt(i, 0) != null) {// se houver algum valor na coluna 0 cont++
                cont++;
            }
        }

        if (cont > 0) {// se existe valores o contador será maior que zero
            if (indice != -1) {// se algum item estiver selecionado o valor sempre será maior que -1 já que o menor indice da matriz é zero  // pergunta ao excluir
                if (JOptionPane.showConfirmDialog(null, "Deseja excluir este Cadastro ?") == 0) {
                    Object Mat = tblclientes.getValueAt(indice, 0);
                    int id_cli = Integer.parseInt(Mat.toString());
                    try {
                        Class.forName("com.mysql.jdbc.Driver").newInstance();
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/coffe_", "root", "");
                        Statement stmt = (Statement) conn.createStatement();
                        String query = "delete from cliente where id_cli = '" + id_cli + "'";
                        stmt.executeUpdate(query);

                        JOptionPane.showMessageDialog(null, "Cadastro Deletado");
                        //Estoque s = new Estoque();
                        //s.setVisible(true);
                        //this.dispose();
                    } catch (SQLException s) {
                        System.out.println(s.toString());
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(cad_cli_bean.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(cad_cli_bean.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(cad_cli_bean.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Deve selecionar um Cadstro para excluir.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não existem Cadastro para remover.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/coffe_", "root", "");
            java.sql.Statement st = conn.createStatement();
            st.executeUpdate("UPDATE cliente SET nome_cli='"
                    + this.txtnome.getText() + "',cpf_cli='"
                    + this.txtcpf.getText() + "',endereco_cli='"
                    + this.txtendereco.getText() + "',telefone_cli='"
                    + this.txttelefone.getText() + "',email_cli='"
                    + this.txtemail.getText()
                    + "' WHERE id_cli='" + this.txtid.getText() + "'");
            JOptionPane.showMessageDialog(rootPane, "cliente atualizado");
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } catch (InstantiationException ex) {
            Logger.getLogger(tela_cadastro_client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(tela_cadastro_client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastro_client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}