/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bean.cad_func_bean;
import conexao.ConnectionConexao;
import dao.cad_func_dao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16127512021.2
 */
public class tela_cadastro_func extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastro
     */
    public tela_cadastro_func() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfuncionario = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        txtacesso = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsenha1 = new javax.swing.JTextField();
        txtid1 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionários");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 80, 30));

        tblfuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "cpf", "endereço", "telefone", "email", "usuário", "senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblfuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblfuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblfuncionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 620, 110));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 80, 30));

        jButton7.setText("Limpar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 270, 70, 30));
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 290, 50));

        jButton6.setText("Alterar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 230, 80, 30));

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 51, 0));
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 120, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Usuário:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Endereço");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("CPF:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 0));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 190, -1));
        getContentPane().add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 200, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 190, -1));
        getContentPane().add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, -1));
        getContentPane().add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 170, -1));
        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, -1));

        txtacesso.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        txtacesso.setForeground(new java.awt.Color(153, 51, 0));
        getContentPane().add(txtacesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 90, 20));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("Senha:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(txtsenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, -1));

        txtid1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        txtid1.setForeground(new java.awt.Color(153, 51, 0));
        getContentPane().add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 90, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tela_principal s = new tela_principal();
        s.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = ConnectionConexao.abrirConexao();
        cad_func_bean cb = new cad_func_bean();
        cad_func_dao cd = new cad_func_dao(con);

//cb.setCod_func(txtcodfunc.getText());
        cb.setNome_fun(txtnome.getText());
        cb.setCpf_fun(txtcpf.getText());
        cb.setEndereco_fun(txtendereco.getText());
        cb.setTelefone_fun(txttelefone.getText());
        cb.setEmail_fun(txtemail.getText());
        cb.setLogin_fun(txtlogin.getText());
        cb.setLogin_fun(txtsenha1.getText());

        lblMensagem.setText(cd.inserir(cb));
        ConnectionConexao.fecharConexao(con);
//txtcodfunc.setText ("");
        txtnome.setText("");
        txtcpf.setText("");
        txtendereco.setText("");
        txttelefone.setText("");
        txtemail.setText("");
        txtlogin.setText("");
        txtsenha1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Connection con = ConnectionConexao.abrirConexao();
        cad_func_dao cd = new cad_func_dao(con);
        List<cad_func_bean> listaFuncionario = new ArrayList<cad_func_bean>();
        listaFuncionario = cd.listarTodos();
        DefaultTableModel tbm = (DefaultTableModel) tblfuncionario.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (cad_func_bean cb : listaFuncionario) {
            tbm.addRow(new String[1]);
            tblfuncionario.setValueAt(cb.getId_fun(), i, 0);
            tblfuncionario.setValueAt(cb.getNome_fun(), i, 1);
            tblfuncionario.setValueAt(cb.getCpf_fun(), i, 2);
            tblfuncionario.setValueAt(cb.getEndereco_fun(), i, 3);
            tblfuncionario.setValueAt(cb.getTelefone_fun(), i, 4);
            tblfuncionario.setValueAt(cb.getEmail_fun(), i, 5);
            tblfuncionario.setValueAt(cb.getLogin_fun(), i, 6);
            tblfuncionario.setValueAt(cb.getSenha_fun(), i, 7);

            i++;
        }
        ConnectionConexao.fecharConexao(con);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblfuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblfuncionarioMouseClicked
        int linha_selecionada = tblfuncionario.getSelectedRow();

        txtacesso.setText(tblfuncionario.getValueAt(linha_selecionada, 0).toString());
        txtnome.setText(tblfuncionario.getValueAt(linha_selecionada, 1).toString());
        txtcpf.setText(tblfuncionario.getValueAt(linha_selecionada, 2).toString());
        txtendereco.setText(tblfuncionario.getValueAt(linha_selecionada, 3).toString());
        txttelefone.setText(tblfuncionario.getValueAt(linha_selecionada, 4).toString());
        txtemail.setText(tblfuncionario.getValueAt(linha_selecionada, 5).toString());
        txtlogin.setText(tblfuncionario.getValueAt(linha_selecionada, 6).toString());
        txtsenha1.setText(tblfuncionario.getValueAt(linha_selecionada, 7).toString());
    }//GEN-LAST:event_tblfuncionarioMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int cont = 0;
        int indice = tblfuncionario.getSelectedRow(); // mostra o valor da linha selecionada
        // conta quantas pessoas estão selecionadas na tabela obs: i = linha e 0 = coluna. obs: matriz
        for (int i = 0; i < tblfuncionario.getRowCount(); i++) { // percorre todas as linhas da tabela para verificar a existência de itens
            if (tblfuncionario.getValueAt(i, 0) != null) {// se houver algum valor na coluna 0 cont++
                cont++;
            }
        }

        if (cont > 0) {// se existe valores o contador será maior que zero
            if (indice != -1) {// se algum item estiver selecionado o valor sempre será maior que -1 já que o menor indice da matriz é zero  // pergunta ao excluir
                if (JOptionPane.showConfirmDialog(null, "Deseja excluir este Cadastro ?") == 0) {
                    Object Mat = tblfuncionario.getValueAt(indice, 0);
                    int id_fun = Integer.parseInt(Mat.toString());
                    try {
                        Class.forName("com.mysql.jdbc.Driver").newInstance();
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/coffe_", "root", "");
                        Statement stmt = (Statement) conn.createStatement();
                        String query = "delete from funcionario where id_fun = '" + id_fun + "'";
                        stmt.executeUpdate(query);

                        JOptionPane.showMessageDialog(null, "Cadastro Deletado");
                        //Estoque s = new Estoque();
                        //s.setVisible(true);
                        //this.dispose();
                    } catch (SQLException s) {
                        System.out.println(s.toString());
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(cad_func_bean.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(cad_func_bean.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(cad_func_bean.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Deve selecionar um Cadstro para excluir.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não existem Cadastro para remover.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/coffe_", "root", "");
            java.sql.Statement st = conn.createStatement();
            st.executeUpdate("UPDATE funcionario SET nome_fun='"
                    + this.txtnome.getText() + "',cpf_fun='"
                    + this.txtcpf.getText() + "',endereco_fun='"
                    + this.txtendereco.getText() + "',telefone_fun='"
                    + this.txttelefone.getText() + "',email_fun='"
                    + this.txtemail.getText() + "',login_fun='"
                    + this.txtlogin.getText() + "',senha_fun='"
                    + this.txtsenha1.getText()
                    + "' WHERE id_fun='" + this.txtacesso.getText() + "'");
            JOptionPane.showMessageDialog(rootPane, "cliente atualizado");
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } catch (InstantiationException ex) {
            Logger.getLogger(tela_cadastro_client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(tela_cadastro_client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        txtacesso.setText("");
        txtnome.setText("");
        txtcpf.setText("");
        txtendereco.setText("");
        txttelefone.setText("");
        txtemail.setText("");
        txtlogin.setText("");
        txtsenha1.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastro_func().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTable tblfuncionario;
    private javax.swing.JLabel txtacesso;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JLabel txtid1;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsenha1;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
