/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bean.cad_prod_bean;
import conexao.ConnectionConexao;
import dao.cad_prod_dao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16127512021.2
 */
public class tela_cadastro_prod extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastro_prod
     */
    public tela_cadastro_prod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtid = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprodutos = new javax.swing.JTable();
        lblMensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtquantidade = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        txtid.setForeground(new java.awt.Color(153, 51, 0));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 90, 20));

        jButton6.setText("Limpar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        jButton5.setText("Alterar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 30));

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        tblprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "descrição", "quantidade", "valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprodutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblprodutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 610, 110));
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quantidade:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Descrição:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 160, -1));
        getContentPane().add(txtquantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, -1));
        getContentPane().add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, -1));
        getContentPane().add(txtdescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, -1));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 0));
        jButton1.setText("Cadastrar Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 200, 200, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = ConnectionConexao.abrirConexao();
        cad_prod_bean cb = new cad_prod_bean();
        cad_prod_dao cd = new cad_prod_dao(con);

//cb.setCod_func(txtcodfunc.getText());
        cb.setNome_prod(txtnome.getText());
        cb.setQuantidade_prod(txtquantidade.getText());
        cb.setValor_prod(txtvalor.getText());
        cb.setDescricao_prod(txtdescricao.getText());

        lblMensagem.setText(cd.inserir(cb));
        ConnectionConexao.fecharConexao(con);
//txtcodfunc.setText ("");
        txtnome.setText("");
        txtquantidade.setText("");
        txtvalor.setText("");
        txtdescricao.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection con = ConnectionConexao.abrirConexao();
        cad_prod_dao cd = new cad_prod_dao(con);
        List<cad_prod_bean> listaProduto = new ArrayList<cad_prod_bean>();
        listaProduto = cd.listarTodos();
        DefaultTableModel tbm = (DefaultTableModel) tblprodutos.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (cad_prod_bean cb : listaProduto) {
            tbm.addRow(new String[1]);
            tblprodutos.setValueAt(cb.getId_prod(), i, 0);
            tblprodutos.setValueAt(cb.getNome_prod(), i, 1);
            tblprodutos.setValueAt(cb.getDescricao_prod(), i, 2);
            tblprodutos.setValueAt(cb.getQuantidade_prod(), i, 3);
            tblprodutos.setValueAt(cb.getValor_prod(), i, 4);

            i++;
        }
        ConnectionConexao.fecharConexao(con);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int cont = 0;
        int indice = tblprodutos.getSelectedRow(); // mostra o valor da linha selecionada
        // conta quantas pessoas estão selecionadas na tabela obs: i = linha e 0 = coluna. obs: matriz
        for (int i = 0; i < tblprodutos.getRowCount(); i++) { // percorre todas as linhas da tabela para verificar a existência de itens
            if (tblprodutos.getValueAt(i, 0) != null) {// se houver algum valor na coluna 0 cont++
                cont++;
            }
        }

        if (cont > 0) {// se existe valores o contador será maior que zero
            if (indice != -1) {// se algum item estiver selecionado o valor sempre será maior que -1 já que o menor indice da matriz é zero  // pergunta ao excluir
                if (JOptionPane.showConfirmDialog(null, "Deseja excluir este Cadastro ?") == 0) {
                    Object Mat = tblprodutos.getValueAt(indice, 0);
                    int id_prod = Integer.parseInt(Mat.toString());
                    try {
                        Class.forName("com.mysql.jdbc.Driver").newInstance();
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/coffe_", "root", "");
                        Statement stmt = (Statement) conn.createStatement();
                        String query = "delete from produto where id_prod = '" + id_prod + "'";
                        stmt.executeUpdate(query);

                        JOptionPane.showMessageDialog(null, "Cadastro Deletado");
                        //Estoque s = new Estoque();
                        //s.setVisible(true);
                        //this.dispose();
                    } catch (SQLException s) {
                        System.out.println(s.toString());
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(cad_prod_bean.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(cad_prod_bean.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(cad_prod_bean.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Deve selecionar um Cadstro para excluir.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não existem Cadastro para remover.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/coffe_", "root", "");
            java.sql.Statement st = conn.createStatement();
            st.executeUpdate("UPDATE produto SET nome_prod='"
                    + this.txtnome.getText() + "',quantidade_prod='"
                    + this.txtquantidade.getText() + "',valor_prod='"
                    + this.txtvalor.getText() + "',descricao_prod='"
                    + this.txtdescricao.getText()
                    + "' WHERE nome_prod='" + this.txtnome.getText() + "'");
            JOptionPane.showMessageDialog(rootPane, "produto atualizado");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(tela_cadastro_prod.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(tela_cadastro_prod.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(tela_cadastro_prod.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(tela_cadastro_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprodutosMouseClicked
        int linha_selecionada = tblprodutos.getSelectedRow();

        txtid.setText(tblprodutos.getValueAt(linha_selecionada, 0).toString());
        txtnome.setText(tblprodutos.getValueAt(linha_selecionada, 1).toString());
        txtdescricao.setText(tblprodutos.getValueAt(linha_selecionada, 2).toString());
        txtquantidade.setText(tblprodutos.getValueAt(linha_selecionada, 3).toString());
        txtvalor.setText(tblprodutos.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_tblprodutosMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtid.setText("");
        txtnome.setText("");
        txtquantidade.setText("");
        txtvalor.setText("");
        txtdescricao.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastro_prod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTable tblprodutos;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtquantidade;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
